### ISSUE TITLE
Duplicate Coal and Charcoal Recipes

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#1]
1 Coal shapeless craft into 8 Fuel Pellet (Progressive Automation)
1 Coal shapeless craft into 8 Fragmented Carbon (Galacticraft) <-- Default recipe

1 Charcoal shapeless craft into 8 Fuel Pellet (Progressive Automation)
1 Charcoal shapeless craft into 4 Fragmented Carbon (Galacticraft) <-- Default recipe

**Comment by blade1981m** [comment]
Labelled as bug due to not being able to create fuel pellets.
