### ISSUE TITLE
Unable to craft wooden/stone Hoe

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#10]
Agricraft disables the ability to craft wood and stone hoes due to the "disable vanilla farming" setting.  There is no option to explicitly turn them back on, so it may be best to create a new crafting recipe for them so other mods may use the items for crafting.  Iguana's still makes the hoes useless so it doesn't interfere with Agricraft's intentions.

**Comment by shaggy1395** [comment]
Updated HungerOverhaul setting to enable vanilla hoe crafting.
Resolved with pull request #12

**Comment by blade1981m** [comment]
Labeling as bug as this prevents recipes that require hoes from being completed, such as Progressive Automation Planter

**Comment by blade1981m** [comment]
Issue resolved by changing Hunger Overhaul config setting in pull request #12.
