### ISSUE TITLE
IE Industrial Hemp Seeds cannot be planted

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#13]
Agricraft disables the ability to plant any seed on vanilla farmland. Most other mods can be planted on Agricraft crops, but not IE Hemp.

The hemp can be planted in MFR Fertile Soil and RandomThings Fertilized Dirt, as can all other seeds which bypasses Agricraft.  Agricraft has an option to disable this, but I'm not sure it should be disabled.

**Comment by blade1981m** [comment]
Will be fixed in next agricraft update per InfinityRaider/AgriCraft#269

**Comment by blade1981m** [comment]
Resolved in v1.0.0 release by updating to AgriCraft beta version
