### ISSUE TITLE
Botania Fruit of Grisaia doesn't restore health

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#21]
The fruit should restore full health and saturation when eaten.  Instead it repeatedly plays the eating sound and animation but doesn't restore any health.  Possibly related to changes made by Spice of Life or Hunger Overhaul.

**Comment by blade1981m** [comment]
Fruit of Grisaia requires mana. Tested and verified that with a mana tablet the fruit works as intended.
