### ISSUE TITLE
Unable to craft Wax Capsules with Pam's wax

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#27]
NEI lists a shaped recipe for 3 Pam's wax to make 3 wax capsules from forestry.  When trying to craft that recipe, there is no output item.  Shift clicking the ? will put the items into the crafting grid in the appropriate spots but it still will not allow the item to be crafted.

**Comment by shaggy1395** [comment]
If possible, it would be best to correct the recipe to require 3 OreDict materialPressedwax to use both Pam's wax and beeswax.

**Comment by blade1981m** [comment]
Commit resolved issue.
