### ISSUE TITLE
Unable to collect Railcraft Creosote Bottles

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#28]
Putting glass bottles in the railcraft coke oven produces Immersive Engineering creosote bottles, which can't be used to craft wooden rail ties.  

Possible fixes:
- A recipe for wooden rail ties using IE creosote
- A recipe to convert IE creosote bottles into Railcraft version
- Re-enable the creation of Railcraft creosote bottles from the Railcraft coke oven

**Comment by blade1981m** [comment]
Updated Railcraft to resolve this.
