### ISSUE TITLE
Crash while browsing NEI - IE Steel Ingot

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#4]
I was looking at Immersive Engineering in NEI to find out how to craft Steel Ingots.  I clicked right a couple times to cycle through the crafting types then it crashed.  It happened immediately after the Blast Furnace recipes.  Other ingots don't seem to have this problem.

It's easy to reproduce, happens every time.  Not sure which logs you need so let me know what to get.

**Comment by blade1981m** [comment]
Awaiting on new release of Immersive Engineering. Problem reported in BluSunrize/ImmersiveEngineering#373
