### ISSUE TITLE
Pneumaticraft - No seeds

### ISSUE THREAD

**Issue by shaggy1395** [blade1981m/YAKS-Pack#5]
It seems all seeds have been disabled in the config.  If this is intentional, the mod is entirely unusable.  Do you intend to enable some other method of seed gathering, or a different method of making the plastics required for the mod?

**Comment by shaggy1395** [comment]
Apparently not a bug, but an undocumented change to the progression of the mod.

Recommend installing in-game wiki mod to assist in starting with the mod.  http://minecraft.curseforge.com/mc-mods/223815-in-game-wiki-mod

**Comment by blade1981m** [comment]
Closing as seeds were deprecated since PneumaticCraft 1.8.
